src/objects/ChildObject__c.object
<CustomObject>
    <fields>
        <fullName>Log__c</fullName>
        <label>Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ParentObject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ParentObject</label>
        <referenceTo>ParentObject__c</referenceTo>
        <relationshipLabel>ChildObjects</relationshipLabel>
        <relationshipName>ChildObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ChildObject</label>
    <nameField>
        <label>ChildObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChildObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GrandChildObject__c.object
<CustomObject>
    <fields>
        <fullName>ChildObject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ChildObject</label>
        <referenceTo>ChildObject__c</referenceTo>
        <relationshipLabel>GrandParentObjects</relationshipLabel>
        <relationshipName>GrandParentObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <label>GrandChildObject</label>
    <nameField>
        <label>GrandChildObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GrandChildObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ParentObject__c.object
<CustomObject>
    <fields>
        <fullName>Log__c</fullName>
        <label>Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <label>ParentObject</label>
    <nameField>
        <label>ParentObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ParentObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SignalForParent.cls
/**
 * Created by valeriyartemenko on 06.04.17.
 */

public with sharing class SignalForParent {
    public static void changeMessageChild(List<GrandChildObject__c> grandChildObjects) {
        mainMethodForChangeMessageChild(grandChildObjects);
    }
    public static void changeMessageParetn(List<ChildObject__c> grandChildObjects){
        mainMethodForChangeMessageParent(grandChildObjects);
    }


    public static void mainMethodForChangeMessageChild(List<GrandChildObject__c> grandChildObjects) {
        Set<Id> key = new Set<Id>();
        for (GrandChildObject__c child : grandChildObjects)
            key.add(child.ChildObject__c);

        List<ChildObject__c> idChild = [Select id, message__c from ChildObject__c where id in :key];
        for (Integer i = 0; i < idChild.size(); i++) {
            for (Integer j = 0; j < grandChildObjects.size(); j++) {
                if (idChild.get(i).id == grandChildObjects.get(j).ChildObject__c) {
                    idChild.get(i).message__c = grandChildObjects.get(j).message__c;
                    idChild.get(i).Log__c = system.today().format() + ' ' + grandChildObjects.get(j).Name + ' ' + grandChildObjects.get(i).message__c;
                }
            }
        }
        upsert idChild;
    }

    public static void mainMethodForChangeMessageParent(List<ChildObject__c> grandChildObjects) {
        Set<Id> key = new Set<Id>();
        for (ChildObject__c child : grandChildObjects)
            key.add(child.ParentObject__c);

        List<ParentObject__c> idChild = [Select id, message__c from ParentObject__c where id in :key];
        for (Integer i = 0; i < idChild.size(); i++) {
            for (Integer j = 0; j < grandChildObjects.size(); j++) {
                if (idChild.get(i).id == grandChildObjects.get(j).ParentObject__c) {
                    idChild.get(i).message__c = grandChildObjects.get(j).message__c;
                    idChild.get(i).Log__c = system.today().format() + ' ' + grandChildObjects.get(j).Name + ' ' + grandChildObjects.get(i).message__c;

                }
            }
        }
        upsert idChild;
    }

    public static void getLog(List<GrandChildObject__c> grandChildObjects) {
        Set<Id> key = new Set<Id>();
        for (GrandChildObject__c child : grandChildObjects)
            key.add(child.ChildObject__c);

        List<ChildObject__c> idChild = [Select id, message__c from ChildObject__c where id in :key];
        for (Integer i = 0; i < idChild.size(); i++) {
            for (Integer j = 0; j < grandChildObjects.size(); j++)
                if (idChild.get(i).id == grandChildObjects.get(j).ChildObject__c) {
                    idChild.get(i).Log__c = system.today().format() + ' ' + grandChildObjects.get(j).Name + ' ' + grandChildObjects.get(i).message__c;
                }
        }
        upsert idChild;
    }
}